### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Nick-Mazuk** [finale-lua/lua-scripts#383] opened 2022-12-04 02:15 UTC
**Description**

Having an issue with the Hairpin Creator script. I get an error message about an unfinished string whenever I try to run any of the included scripts in this set.

**Metadata**

- Finale v27
- macOS 12
- Script: hairpin_creator.lua

_Created through the website by Noah Turner noahdude412@gmail.com_

**Comment by ThistleSifter** [comment] 2022-12-04 11:08
This is caused by an issue with the bundler. I'll submit a fix for this shortly.

**Comment by Nick-Mazuk** [comment] 2022-12-04 16:18
Thanks @ThistleSifter for fixing this!

**Closed** 2022-12-04 16:17 UTC
Labels: bug
