### ISSUE TITLE
[BUG] Weird error message from Lua Syntax Check

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#161] opened 2022-04-28 14:07 UTC
Does anyone have any idea what's causing this message?

```
<doc name> expected. Lua Syntax Check.(lua-miss-cate-name)
```

It occurs after some (but not all) open multiline comment brackets.

**Comment by rpatters1** [comment] 2022-04-28 14:24
Okay, I figured out what's causing it but not how to solve it. The syntax checker does not like the `[optional_parameter]` brackets inside the comments. If you remove the brackets, the problem goes away.

I wonder if there is a config option to suppress this warning.

**Comment by Nick-Mazuk** [comment] 2022-04-29 01:03
Can you link to a specific line of code where you're seeing that error? I've not seen that error on my machine. Maybe I'm just looking in the wrong spot, though.

**Comment by rpatters1** [comment] 2022-04-29 01:16
For example:

https://github.com/finale-lua/lua-scripts/blob/4ccbee652ec78b34861145952e048347fb1c39cf/src/library/general_library.lua#L241

It's basically any library function with optional parameters, and what's causing the message is the open bracket `[` on the optional paramter.

**Comment by Nick-Mazuk** [comment] 2022-04-29 15:50
I see the error and root cause. Essentially, it seems like the Lua Linter is expecting Lua doc and not our modified version.

To fix, you just need to update this line in the VS Code settings (I'm updating #156 to reflect this) from:

```json
"Lua.diagnostics.disable": ["lowercase-global"],
```

to:

```json
"Lua.diagnostics.disable": ["lowercase-global", "luadoc-miss-cate-name"],
```

**Comment by Nick-Mazuk** [comment] 2022-07-29 04:45
Closing because I think this is resolved. Feel free to reopen if it isn't.

**Closed by Nick-Mazuk** 2022-07-29 04:45 UTC
Labels: bug
